apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: lvv2pg0k4-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:bfa25f09e828b212e5af5481d051948bf7b50523@sha256:215ed8ccb838f1c1ed5f46a71e6896ff483e92209216827ddfaec3c89c14e69e
        name: container-image  
